name: diy-action-2
on: 
  workflow_dispatch:
    inputs:
      ref:
        description: '分支或标签(正式使用的时候不要给默认值)'
        default: 'svn-python-demo-2.0.0'
        required: true
        type: string

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: 拉取代码
        id: foo
        uses: deming-org/action-checkout@main
        with:
          repository: '${{ secrets.SVN_SERVER }}'
          ref: ${{ inputs.ref }}
          repo_type: 'svn'
          username: ${{ secrets.SVN_USER }}
          password: ${{ secrets.SVN_PWD }}
      - name: 验证
        run: |
          pwd && ls -lt
          # svn --username ${{ secrets.SVN_USER }} --password ${{ secrets.SVN_PWD }} log || echo -e "\033[31m 查看提交信息失败\033[om"
      - name: 上面有步骤失败才执行
        if: ${{ failure() }}
        run: |
          pwd && ls -lt
          echo -e "\033[31m前面有步骤失败了\033[0m"
