name: diy-action-2
on: 
  workflow_dispatch:
    inputs:
      ref:
        description: '分支或标签(正式使用的时候不要给默认值)'
        default: 'svn-python-demo-2.0.0'
        required: true
        type: string

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: 拉取代码
        id: foo
        uses: deming-org/action-checkout@main
        with:
          repository: '${{ secrets.SVN_SERVER }}'
          ref: ${{ inputs.ref }}
          repo_type: 'svn'
          username: ${{ secrets.SVN_USER }}
          password: ${{ secrets.SVN_PWD }}
      - name: 验证
        run: pwd && ls -lt
