on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4.1.1
      - id: foo
        uses: deming-org/diyactions-test@v1
        with:
          who-to-greet: 'Deming'
      - name: 获取步骤输出
        run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
